print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun")
print("Yay! Printing.")
print("I'd much rather you 'not'.")
print('I "said" do not touch this.')
print("This textbook is too simple")
print("I think I can conquer it.")
#The two Above is a extra practice sentences.
